apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-azure-resources
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/azure_resources
    repoURL: https://github.com/samuelkaeser/azure-gitops.git
    targetRevision: testing/gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true