apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
kind: ProviderConfig
spec:
  credentials:
    source: SystemAssignedManagedIdentity
  clientID: 4e65de39-a5c5-4e32-89a0-d82c1b3ef22b
  subscriptionID: da12d467-03ae-4675-aa29-d3b26fdbd2cc
  tenantID: a9080dcf-8589-4cb6-a2e2-21398dc6c671