apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
kind: ProviderConfig
spec:
  credentials:
    source: UserAssignedManagedIdentity
  clientID: a36d54d3-f359-49d1-a5de-85aa32319329
  subscriptionID: da12d467-03ae-4675-aa29-d3b26fdbd2cc
  tenantID: a9080dcf-8589-4cb6-a2e2-21398dc6c671