apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
kind: ProviderConfig
spec:
  credentials:
    source: UserAssignedManagedIdentity
  clientID: defa4594-bf14-40a4-8c58-22402ef6b0d8
  subscriptionID: da12d467-03ae-4675-aa29-d3b26fdbd2cc
  tenantID: a9080dcf-8589-4cb6-a2e2-21398dc6c671