apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
kind: ProviderConfig
spec:
  credentials:
    source: UserAssignedManagedIdentity
  clientID: 8c4cde32-f90d-490e-a186-074559ff975c
  subscriptionID: da12d467-03ae-4675-aa29-d3b26fdbd2cc
  tenantID: a9080dcf-8589-4cb6-a2e2-21398dc6c671