apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.16.0
    chart: crossplane
    helm:
      releaseName: crossplane-stable
      values: |
        jobservice:
          replicas: 1
        registry:
          replicas: 1
        persistence:
          persistentVolumeClaim:
            registry:
              size: 10Gi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: prometheus-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true